# Generated by Django 3.2.7 on 2022-05-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20220518_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buyer_info',
        ),
        migrations.AddField(
            model_name='placeorder',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='email',
            field=models.EmailField(blank=True, error_messages={'null': 'This feild cannot be null'}, max_length=255, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='orderNotes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='shipAddress',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='shipArea',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BuyerInfo',
        ),
    ]
