# Generated by Django 3.2.7 on 2022-05-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20220518_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
