# Generated by Django 3.2.7 on 2022-05-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_auto_20220520_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='email',
            field=models.EmailField(blank=True, error_messages={'null': 'This feild cannot be null'}, max_length=255, null=True, verbose_name='email'),
        ),
    ]
