# Generated by Django 3.2.7 on 2022-06-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_alter_placeorder_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='product',
        ),
        migrations.AddField(
            model_name='placeorder',
            name='product',
            field=models.ManyToManyField(to='Product.Product'),
        ),
    ]
