# Generated by Django 3.2.7 on 2022-06-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_auto_20220605_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
        migrations.AddField(
            model_name='placeorder',
            name='paymentMethod',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit/Debit', 'Credit/Debit')], max_length=100, null=True),
        ),
    ]
