# Generated by Django 4.0.5 on 2022-06-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_auto_20220607_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='quantity',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
