# Generated by Django 4.0.5 on 2022-06-08 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0014_alter_placeorder_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='seller',
        ),
        migrations.AddField(
            model_name='placeorder',
            name='seller',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
