# Generated by Django 3.2.7 on 2022-12-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_remove_placeorder_seller_placeorder_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
