# Generated by Django 3.2.7 on 2022-11-03 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserAllMessage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
